[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

upload_port = /dev/ttyUSB0

; Tải thư viện micro-ROS trực tiếp từ GitHub
lib_deps = 
    https://github.com/micro-ROS/micro_ros_platformio
    https://github.com/micro-ROS/micro_ros_arduino.git

; Cấu hình môi trường cho micro-ROS
build_flags =
    -L ./.pio/libdeps/esp32dev/micro_ros_arduino/src/esp32/
    -l microros
    -D RMW_UXRCE_MAX_NODES=1
    -D RMW_UXRCE_MAX_PUBLISHERS=1
    -D RMW_UXRCE_MAX_SUBSCRIPTIONS=1
    -D RMW_UXRCE_MAX_CLIENTS=0
    -D RMW_UXRCE_MAX_SERVICES=0
    -D RMW_UXRCE_MAX_HISTORY=1
    -D RMW_UXRCE_STREAM_HISTORY=1
    -D UXR_CUSTOM_SERIAL_BUFFER_SIZE=2048 ;
board_microros_distro = humble
board_microros_transport = wifi